# Generated by Django 4.2.5 on 2023-09-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('cel_inqui', models.CharField(max_length=16)),
                ('CPF', models.CharField(max_length=13)),
            ],
        ),
    ]
