# Generated by Django 4.2.5 on 2024-10-06 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Casa', '0015_delete_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cartao', models.CharField(max_length=16)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Casa.casa')),
                ('reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Casa.reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
