# Generated by Django 4.2.5 on 2023-11-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('num_quarto', models.IntegerField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_banheiro', models.IntegerField()),
                ('descricao', models.TextField()),
                ('area', models.TextField()),
            ],
        ),
    ]
