# Generated by Django 4.2.5 on 2023-11-04 20:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Casa', '0002_casa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='usuario',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
