# Generated by Django 4.2.5 on 2023-11-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0004_alter_casa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='imagem',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
