# Generated by Django 4.2.5 on 2023-11-11 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0005_casa_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='imagem',
        ),
    ]
