# Generated by Django 4.2.5 on 2023-11-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0006_remove_casa_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_casas/'),
        ),
    ]
