# Generated by Django 4.2.5 on 2023-11-28 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0008_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_final',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
