# Generated by Django 4.2.5 on 2023-11-28 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0010_reserva_data_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data_Inicial',
        ),
    ]
