# Generated by Django 4.2.5 on 2024-10-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Casa', '0014_pagamento_reserva'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
